import { z } from "zod"

// Zod validation layer for User schema
// Check the prisma if this schema is based on it's corresponding model

export const userSchema = z.object({
    id: z.string().optional(),
    name: z.string().min(1, "Name is required"),
    email: z.email("Invalid email"),
    reminderTime: z.string().default("9:00"),
    timezone: z.string().default("Asia/Manila"),
    createdAt: z.date().optional(), // optional fields are auto-generated by prisma
});

// Can reuse UserInput type in frontend forms or API route
export type UserInput = z.infer<typeof userSchema>; // convert the userSchema into ts type

